### ISSUE TITLE
Analyze division by zero-bitvector, modulo/remainder by zero

### ISSUE THREAD

**Issue by samuelgruetter** [epfl-lara/leon#114]
In this example, Leon tells us that in `b1`, no division by zero will occur. But it could also analyze the other cases for division or modulo by zero.

```scala
object Test {
  def b1: BigInt = BigInt(5) / BigInt(2)
  def b2: BigInt = BigInt(5) % BigInt(2)
  def b3: BigInt = BigInt(5) mod BigInt(2)

  def i1: Int = 5 / 2
  def i2: Int = 5 % 2
}
```

```
[  Info  ]   ┌──────────────────────┐
[  Info  ] ╔═╡ Verification Summary ╞═══════════════════════════════════════════════════════════════════╗
[  Info  ] ║ └──────────────────────┘                                                                   ║
[  Info  ] ║ b1     division by zero                       3:20       valid        Z3-f           0.025 ║
[  Info  ] ╟┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╢
[  Info  ] ║ total: 1      valid: 1      invalid: 0      unknown 0                                0.025 ║
[  Info  ] ╚════════════════════════════════════════════════════════════════════════════════════════════╝
```

[Not so important, just a little enhancement ;-)]

**Comment by regb** [comment]
Hi,

It's a cool feature to have so I just added support for detecting modulo 
and remainder by zero as well. Though it is currently only
available in a branch because it seems to cause a bug in Repair:
https://github.com/regb/leon/tree/topic/rembyzero

Note that in your test the operations on Int are simplified by the Scala 
compiler front-end, so you will need to write something like:

   object Test {
     def b1: BigInt = BigInt(5) / BigInt(2)
     def b2: BigInt = BigInt(5) % BigInt(2)
     def b3: BigInt = BigInt(5) mod BigInt(2)

     def f1(i: Int): Int = i / 2
     def f2(i: Int): Int = i % 2
   }

to actually see the verification conditions.

**Comment by vkuncak** [comment]
This is now merged?

**Comment by regb** [comment]
yes it is
