### ISSUE TITLE
Web interface appears to be failing

### ISSUE THREAD

**Issue by eglassman** [epfl-lara/leon#310]
... to authenticate users or load synthesis examples.

**Comment by eglassman** [comment]
I get this when I select List Insert:
![image](https://cloud.githubusercontent.com/assets/2320194/26809137/610e442a-4a30-11e7-88f3-9f5d26314033.png)
and I get this when I try to login with Github:
![image](https://cloud.githubusercontent.com/assets/2320194/26809146/74fe33dc-4a30-11e7-8e8f-67494ee9c703.png)

**Comment by larsrh** [comment]
I don't operate these servers, but you might want to try http://leondev.epfl.ch/ instead.

**Comment by MikaelMayer** [comment]
I restarted the server. I'm so sorry. I don't like to blame others, but it looks like it is a recurrent bug due to our use of the Play Framework with actors. From time to time it leaks memory (no kidding) and the back-end fails. I don't know how to solve this problem other than restarting the server. The code is on github.com/epfl-lara/leon-web
